USE mouse_phenotype_database;


ALTER TABLE strain_info 
	CHANGE COLUMN StrainAbbr StrainAbbr VARCHAR(50) NOT NULL,
	ADD PRIMARY KEY (StrainAbbr),
	ADD UNIQUE INDEX StrainAbbr_UNIQUE (StrainAbbr ASC) VISIBLE, 
CHANGE COLUMN OfficialSymbol1 OfficialSymbol1 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN GeneID1 GeneID1 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN GeneID2 GeneID2 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN GeneID3 GeneID3 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN GeneID4 GeneID4 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN OfficialSymbol2 OfficialSymbol2 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN OfficialSymbol3 OfficialSymbol3 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN OfficialSymbol4 OfficialSymbol4 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN OriginLab OriginLab VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN ES_Cell_Line ES_Cell_Line VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN DonorStrain1 DonorStrain1 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN BackgroundStrain BackgroundStrain VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN PIName PIName VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN Experimenter1 Experimenter1 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN Experimenter2 Experimenter2 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN Experimenter3 Experimenter3 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN MutationType1 MutationType1 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN OtherDescriptions OtherDescriptions VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN MouseResourceURL1 MouseResourceURL1 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN MouseResourceURL2 MouseResourceURL2 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN MouseResourceURL3 MouseResourceURL3 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN MouseResourceURL4 MouseResourceURL4 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN Article_Title Article_Title VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN Article_URL Article_URL VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN PMID PMID VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN DonorStrain2 DonorStrain2 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN DonorStrain3 DonorStrain3 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN MutationType2 MutationType2 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN MutationType3 MutationType3 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN MutationType4 MutationType4 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN Article_Title2 Article_Title2 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN Article_URL2 Article_URL2 VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN PMID2 PMID2 VARCHAR(400) NULL DEFAULT NULL ;


ALTER TABLE group_info
	CHANGE COLUMN StrainAbbr StrainAbbr VARCHAR(50) NOT NULL ,
	CHANGE COLUMN GroupID GroupID VARCHAR(50) NOT NULL ,
    CHANGE COLUMN BatchNo BatchNo VARCHAR(15) NULL DEFAULT NULL ,
	CHANGE COLUMN NumberOfCages NumberOfCages TINYINT NULL DEFAULT NULL ,
	ADD PRIMARY KEY (GroupID),
	ADD UNIQUE INDEX GroupID_UNIQUE (GroupID ASC) VISIBLE,
	ADD INDEX fk_group_id_idx (StrainAbbr ASC) VISIBLE,
ADD CONSTRAINT fk_group_id
  FOREIGN KEY (StrainAbbr)
  REFERENCES strain_info (StrainAbbr)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  


-- mouse info

ALTER TABLE mouse_info 

CHANGE COLUMN MouseID MouseID VARCHAR(50) NOT NULL ,
CHANGE COLUMN GroupID GroupID VARCHAR(50) NOT NULL ,
CHANGE COLUMN Gender Gender VARCHAR(50) NOT NULL ,
CHANGE COLUMN Genotype Genotype VARCHAR(50) NOT NULL,
CHANGE COLUMN CageNo CageNo VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN IDinGroup IDinGroup VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN IDinStrain IDinStrain VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN CoatColor CoatColor VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN Identification Identification VARCHAR(45) NULL DEFAULT NULL ,

ADD PRIMARY KEY (MouseID),
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD INDEX fk_mouse_id_idx (GroupID ASC) VISIBLE,
ADD CONSTRAINT fk_mouse_id
  FOREIGN KEY (GroupID)
  REFERENCES group_info (GroupID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  




-- tasks, primary and foreign keys --

-- GHNS t01


ALTER TABLE ghns_t01 
	CHANGE COLUMN GHNS_ID GHNS_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
	CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
	CHANGE COLUMN GHNS_TrialNumber GHNS_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_AgeInDays GHNS_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_Whisker GHNS_Whisker VARCHAR(45) NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_CoatState GHNS_CoatState VARCHAR(45) NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_RightingReflex GHNS_RightingReflex VARCHAR(45) NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_WhiskerTwitch GHNS_WhiskerTwitch VARCHAR(45) NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_EarTwitch GHNS_EarTwitch VARCHAR(45) NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_Reaching GHNS_Reaching VARCHAR(45) NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_KeyJangling GHNS_KeyJangling VARCHAR(45) NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_Notes GHNS_Notes VARCHAR(400) NULL DEFAULT NULL,
    CHANGE COLUMN GHNS_WireHang GHNS_WireHang SMALLINT UNSIGNED NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_GripStrength GHNS_GripStrength DECIMAL(9,3) NULL DEFAULT NULL,
    CHANGE COLUMN GHNS_BodyWeight GHNS_BodyWeight DECIMAL(7,2) NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_RectalTemperature GHNS_RectalTemperature DECIMAL(7,2) NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_RTOrder GHNS_RTOrder TINYINT UNSIGNED NULL DEFAULT NULL,
    CHANGE COLUMN GHNS_Date1 GHNS_Date1 DATE NULL DEFAULT NULL ,
	CHANGE COLUMN GHNS_Date2 GHNS_Date2 DATE NULL DEFAULT NULL ,
    
ADD PRIMARY KEY (GHNS_ID),
	ADD UNIQUE INDEX GHNS_ID_UNIQUE (GHNS_ID ASC) VISIBLE,
	ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_ghns_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


-- of

ALTER TABLE of_sum_t01 

CHANGE COLUMN OF_SUM_ID OF_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN OF_SUM_TrialNumber OF_SUM_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN OF_SUM_Drug OF_SUM_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN OF_SUM_AgeInDays OF_SUM_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN OF_SUM_ExperimentTime OF_SUM_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN OF_SUM_EquipmentNumber OF_SUM_EquipmentNumber TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN OF_SUM_Notes OF_SUM_Notes VARCHAR(400) NULL DEFAULT NULL,
CHANGE COLUMN OF_SUM_ExperimentDate OF_SUM_ExperimentDate DATE NULL DEFAULT NULL,

ADD PRIMARY KEY (OF_SUM_ID),
	ADD UNIQUE INDEX OF_SUM_ID_UNIQUE (OF_SUM_ID ASC) VISIBLE,
	ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_of_sum_mouse_id
	FOREIGN KEY (MouseID)
	REFERENCES mouse_info (MouseID)
	ON DELETE CASCADE
	ON UPDATE CASCADE;


  
  
  
  
  ALTER TABLE of_t01 

CHANGE COLUMN OF_ID OF_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN OF_TrialNumber OF_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN OF_Time OF_Time SMALLINT UNSIGNED NOT NULL ,
CHANGE COLUMN OF_Distance OF_Distance MEDIUMINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN OF_CentTime OF_CentTime DECIMAL(6,2) NULL DEFAULT NULL ,
CHANGE COLUMN OF_VerAct OF_VerAct SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN OF_StCounts OF_StCounts SMALLINT UNSIGNED NULL DEFAULT NULL ,

ADD PRIMARY KEY (OF_ID),
ADD UNIQUE INDEX OF_ID_UNIQUE (OF_ID ASC) VISIBLE,
ADD INDEX fk_of_mouse_id_idx (MouseID ASC) VISIBLE,

ADD CONSTRAINT fk_of_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
 ADD CONSTRAINT un_of_mouse_id_time UNIQUE(MouseID, OF_Time);

  
-- ld
  
ALTER TABLE ld_t01 

CHANGE COLUMN LD_ID LD_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN LD_TrialNumber LD_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN LD_Drug LD_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN LD_ExperimentTime LD_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN LD_ExperimentDate LD_ExperimentDate DATE NULL DEFAULT NULL ,
CHANGE COLUMN LD_LatencyToEnterLight LD_LatencyToEnterLight SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN LD_NumberOfTransitions LD_NumberOfTransitions SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN LD_AgeInDays LD_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN LD_Notes LD_Notes VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN LD_DarkDistance LD_DarkDistance DECIMAL(9,2) NULL DEFAULT NULL ,
CHANGE COLUMN LD_LightDistance LD_LightDistance DECIMAL(9,2) NULL DEFAULT NULL ,
CHANGE COLUMN LD_LightTime LD_LightTime DECIMAL(9,2) NULL DEFAULT NULL ,

ADD PRIMARY KEY (LD_ID),
ADD UNIQUE INDEX LD_ID_UNIQUE (LD_ID ASC) VISIBLE,
ADD INDEX fk_ld_mouse_id_idx (MouseID ASC) VISIBLE,
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,

ADD CONSTRAINT fk_ld_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


-- ep

ALTER TABLE ep_t01 
CHANGE COLUMN EP_ID EP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN EP_TrialNumber EP_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN EP_TotalEntries EP_TotalEntries SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN EP_Drug EP_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN EP_AgeInDays EP_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN EP_ExperimentTime EP_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN EP_ExperimentDate EP_ExperimentDate DATE NULL DEFAULT NULL ,
CHANGE COLUMN EP_TotalDistance EP_TotalDistance DECIMAL(9,2)  NULL DEFAULT NULL ,
CHANGE COLUMN EP_PercentageOpenArmEntries EP_PercentageOpenArmEntries DECIMAL(9,2)  NULL DEFAULT NULL ,
CHANGE COLUMN EP_OpenArmStayRatio EP_OpenArmStayRatio DECIMAL(9,2)  NULL DEFAULT NULL ,
CHANGE COLUMN EP_Notes EP_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD PRIMARY KEY (EP_ID),
ADD UNIQUE INDEX EP_ID_UNIQUE (EP_ID ASC) VISIBLE,
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_ep_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  

-- hp

ALTER TABLE hp_t01 
CHANGE COLUMN HP_ID HP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN HP_TrialNumber HP_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN HP_AgeInDays HP_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN HP_ExperimentTime HP_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN HP_ExperimentDate HP_ExperimentDate DATE NULL DEFAULT NULL ,
CHANGE COLUMN HP_Latency HP_Latency DECIMAL(5,2) NULL DEFAULT NULL ,
CHANGE COLUMN HP_Notes HP_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD PRIMARY KEY (HP_ID),
ADD UNIQUE INDEX HP_ID_UNIQUE (HP_ID ASC) VISIBLE,
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_hp_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

-- fz

ALTER TABLE fz_day1
CHANGE COLUMN FZ_Day1_ID FZ_Day1_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN FZ_Day1_Type FZ_Day1_Type VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day1_Time FZ_Day1_Time TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day1_DV FZ_Day1_DV DECIMAL(7,1) NULL DEFAULT NULL ,

ADD PRIMARY KEY (FZ_Day1_ID),
ADD UNIQUE INDEX FZ_Day1_ID_UNIQUE (FZ_Day1_ID ASC) VISIBLE,
ADD INDEX fk_fz_day1_mouse_id_idx (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_fz_day1_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,

ADD UNIQUE INDEX un_fz_day1_mouse_id_type_time (MouseID ASC, FZ_Day1_Type ASC, FZ_Day1_Time ASC) VISIBLE;


ALTER TABLE fz_day1_sum 
CHANGE COLUMN FZ_Day1_SUM_ID FZ_Day1_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN FZ_Day1_AgeInDays FZ_Day1_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day1_ExperimentTime FZ_Day1_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day1_ExperimentDate FZ_Day1_ExperimentDate DATE NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day1_CountOfShocks FZ_Day1_CountOfShocks TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day1_StrengthOfShock FZ_Day1_StrengthOfShock VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day1_TotalDuration FZ_Day1_TotalDuration SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day1_Drug FZ_Day1_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day1_Notes FZ_Day1_Notes VARCHAR(400) NULL DEFAULT NULL,

ADD PRIMARY KEY (FZ_Day1_SUM_ID),
ADD UNIQUE INDEX FZ_Day1_SUM_ID_UNIQUE (FZ_Day1_SUM_ID ASC) VISIBLE,
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_fz_day1_sum_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
 

  
ALTER TABLE fz_day2 
CHANGE COLUMN FZ_Day2_ID FZ_Day2_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN FZ_Day2_Type FZ_Day2_Type VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day2_Time FZ_Day2_Time TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day2_Experiment FZ_Day2_Experiment VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day2_DV FZ_Day2_DV DECIMAL(7,1) NULL DEFAULT NULL ,

ADD PRIMARY KEY (FZ_Day2_ID),
ADD UNIQUE INDEX FZ_Day2_ID_UNIQUE (FZ_Day2_ID ASC) VISIBLE,
ADD INDEX fk_fz_day2_mouse_id_idx (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_fz_day2_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
 
ADD UNIQUE INDEX un_fz_day2_mouse_id_type_time_exp (MouseID ASC, FZ_Day2_Type ASC, FZ_Day2_Time ASC, FZ_Day2_Experiment ASC) VISIBLE;



ALTER TABLE fz_day2_sum 
CHANGE COLUMN FZ_Day2_SUM_ID FZ_Day2_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN FZ_cont_Day2_AgeInDays FZ_cont_Day2_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cont_Day2_Drug FZ_cont_Day2_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cont_Day2_ExperimentTime FZ_cont_Day2_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cued_Day2_AgeInDays FZ_cued_Day2_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cued_Day2_Drug FZ_cued_Day2_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cued_Day2_ExperimentTime FZ_cued_Day2_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cont_Day2_Notes FZ_cont_Day2_Notes VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cued_Day2_Notes FZ_cued_Day2_Notes VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cont_Day2_ExperimentDate FZ_cont_Day2_ExperimentDate DATE NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cued_Day2_ExperimentDate FZ_cued_Day2_ExperimentDate DATE NULL DEFAULT NULL ,

ADD PRIMARY KEY (FZ_Day2_SUM_ID),
ADD UNIQUE INDEX FZ_Day2_SUM_ID_UNIQUE (FZ_Day2_SUM_ID ASC) VISIBLE,
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_fz_day2_sum_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;



ALTER TABLE fz_day3 
CHANGE COLUMN FZ_Day3_ID FZ_Day3_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN FZ_Day3_Type FZ_Day3_Type VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day3_Time FZ_Day3_Time SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day3_Experiment FZ_Day3_Experiment VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_Day3_DV FZ_Day3_DV DECIMAL(7,1) NULL DEFAULT NULL,

ADD PRIMARY KEY (FZ_Day3_ID),
ADD UNIQUE INDEX FZ_Day3_ID_UNIQUE (FZ_Day3_ID ASC) VISIBLE,
ADD INDEX fk_fz_day3_mouse_id_idx (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_fz_day3_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD UNIQUE INDEX un_fz_day3_mouse_id_type_time_exp (MouseID ASC, FZ_Day3_Type ASC, FZ_Day3_Time ASC, FZ_Day3_Experiment ASC) VISIBLE;
 


ALTER TABLE fz_day3_sum 
CHANGE COLUMN FZ_Day3_SUM_ID FZ_Day3_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN FZ_cont_Day3_AgeInDays FZ_cont_Day3_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cont_Day3_Drug FZ_cont_Day3_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cont_Day3_ExperimentTime FZ_cont_Day3_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cued_Day3_AgeInDays FZ_cued_Day3_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cued_Day3_Drug FZ_cued_Day3_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cued_Day3_ExperimentTime FZ_cued_Day3_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cont_Day3_Notes FZ_cont_Day3_Notes VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN FZ_cued_Day3_Notes FZ_cued_Day3_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD PRIMARY KEY (FZ_Day3_SUM_ID),
ADD UNIQUE INDEX FZ_Day3_SUM_ID_UNIQUE (FZ_Day3_SUM_ID ASC) VISIBLE,
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE, 
ADD CONSTRAINT fk_fz_day3_sum_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


 
-- rr

ALTER TABLE rr_sum_t01 
CHANGE COLUMN RR_SUM_ID RR_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN RR_TrialNumber RR_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN RR_AgeInDays RR_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN RR_Notes RR_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD UNIQUE INDEX RR_SUM_ID_UNIQUE (RR_SUM_ID ASC) VISIBLE,
ADD PRIMARY KEY (RR_SUM_ID),
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_rr_sum_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


ALTER TABLE rr_t01 
CHANGE COLUMN RR_ID RR_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN RR_TrialNumber RR_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN RR_ExperimentTime RR_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN RR_Time RR_Time TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN RR_Latency RR_Latency SMALLINT UNSIGNED NULL DEFAULT NULL ,

ADD PRIMARY KEY (RR_ID),
ADD UNIQUE INDEX RR_ID_UNIQUE (RR_ID ASC) VISIBLE,
ADD INDEX fk_rr_mouse_id_idx (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_rr_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT un_rr_mouse_id_time UNIQUE(MouseID, RR_Time);



-- ppi

ALTER TABLE ppi_t01 
CHANGE COLUMN PPI_ID PPI_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN PPI_TrialNumber PPI_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN PPI_ExperimentTime PPI_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN PPI_Drug PPI_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN PPI_AgeInDays PPI_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN PPI_ASR110 PPI_ASR110 DECIMAL(7,2) NULL DEFAULT NULL ,
CHANGE COLUMN PPI_ASR120 PPI_ASR120 DECIMAL(7,2) NULL DEFAULT NULL ,
CHANGE COLUMN PPI_PPI74_110 PPI_PPI74_110 DECIMAL(7,2) NULL DEFAULT NULL ,
CHANGE COLUMN PPI_PPI74_120 PPI_PPI74_120 DECIMAL(7,2) NULL DEFAULT NULL ,
CHANGE COLUMN PPI_PPI78_110 PPI_PPI78_110 DECIMAL(7,2) NULL DEFAULT NULL ,
CHANGE COLUMN PPI_PPI78_120 PPI_PPI78_120 DECIMAL(7,2) NULL DEFAULT NULL ,
CHANGE COLUMN PPI_Notes PPI_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD PRIMARY KEY (PPI_ID),
ADD UNIQUE INDEX PPI_ID_UNIQUE (PPI_ID ASC) VISIBLE,
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_ppi_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;





-- crsoc

ALTER TABLE crsoc_t01 
CHANGE COLUMN CrSoc_ID CrSoc_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN CrSoc_AgeInDays CrSoc_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_ExperimentTime CrSoc_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_TrialNumber CrSoc_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_NEinCenter CrSoc_NEinCenter SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_NEinLeftArea CrSoc_NEinLeftArea SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_NEinLeftCage CrSoc_NEinLeftCage SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_NEinRightArea CrSoc_NEinRightArea SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_NEinRightCage CrSoc_NEinRightCage SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_Notes CrSoc_Notes VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_TotalDistance CrSoc_TotalDistance DECIMAL(9,2)  NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_AverageSpeed CrSoc_AverageSpeed DECIMAL(9,2)  NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_DistinCenter CrSoc_DistinCenter DECIMAL(9,2)  NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_DistinLeftChamber CrSoc_DistinLeftChamber DECIMAL(9,2)  NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_DistinLeftCup CrSoc_DistinLeftCup DECIMAL(9,2)  NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_DistinRightChamber CrSoc_DistinRightChamber DECIMAL(9,2)  NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_DistinRightCup CrSoc_DistinRightCup DECIMAL(9,2)  NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_STofCenterArea CrSoc_STofCenterArea SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_STofLeftArea CrSoc_STofLeftArea SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_STofLeftCage CrSoc_STofLeftCage SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_STofRightArea CrSoc_STofRightArea SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_STofRightCage CrSoc_STofRightCage SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN CrSoc_SubID CrSoc_SubID VARCHAR(15) NOT NULL,

ADD PRIMARY KEY (CrSoc_ID),
ADD UNIQUE INDEX CrSoc_ID_UNIQUE (CrSoc_ID ASC) VISIBLE,
ADD INDEX fk_crsoc_mouse_id_idx (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_crsoc_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD UNIQUE INDEX un_crsoc_mouse_id_sub (MouseID ASC, CrSoc_SubID ASC) VISIBLE;




-- ps

ALTER TABLE ps_sum_t01 
CHANGE COLUMN PS_Day1_SUM_ID PS_Day1_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN PS_Day1_TrialNumber PS_Day1_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day1_Drug PS_Day1_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day1_AgeInDays PS_Day1_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day1_ExperimentTime PS_Day1_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day1_Notes PS_Day1_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD UNIQUE INDEX PS_Day1_SUM_ID_UNIQUE (PS_Day1_SUM_ID ASC) VISIBLE,
ADD PRIMARY KEY (PS_Day1_SUM_ID),
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_ps_day1_sum_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


ALTER TABLE ps_t01 
CHANGE COLUMN PS_Day1_ID PS_Day1_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN PS_Day1_TrialNumber PS_Day1_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day1_Time PS_Day1_Time TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day1_Immobility PS_Day1_Immobility DECIMAL(6,1) NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day1_Distance PS_Day1_Distance DECIMAL(6,1) NULL DEFAULT NULL ,

ADD PRIMARY KEY (PS_Day1_ID),
ADD UNIQUE INDEX PS_Day1_ID_UNIQUE (PS_Day1_ID ASC) VISIBLE,
ADD INDEX fk_ps_day1_mouse_id_idx (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_ps_day1_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT un_ps_mouse_id_time UNIQUE(MouseID, PS_Day1_Time);




ALTER TABLE ps_sum_t02 
CHANGE COLUMN PS_Day2_SUM_ID PS_Day2_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN PS_Day2_TrialNumber PS_Day2_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day2_Drug PS_Day2_Drug VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day2_AgeInDays PS_Day2_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day2_ExperimentTime PS_Day2_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day2_Notes PS_Day2_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD UNIQUE INDEX PS_Day2_SUM_ID_UNIQUE (PS_Day2_SUM_ID ASC) VISIBLE,
ADD PRIMARY KEY (PS_Day2_SUM_ID),
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE, 
ADD CONSTRAINT fk_ps_day2_sum_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE, 
ADD CONSTRAINT fk_ps_sum_day2_day1
  FOREIGN KEY (MouseID)
  REFERENCES ps_sum_t01 (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;



ALTER TABLE ps_t02 
CHANGE COLUMN PS_Day2_ID PS_Day2_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN PS_Day2_TrialNumber PS_Day2_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day2_Time PS_Day2_Time TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day2_Immobility PS_Day2_Immobility DECIMAL(6,1) NULL DEFAULT NULL ,
CHANGE COLUMN PS_Day2_Distance PS_Day2_Distance DECIMAL(6,1) NULL DEFAULT NULL ,

ADD PRIMARY KEY (PS_Day2_ID),
ADD UNIQUE INDEX PS_Day2_ID_UNIQUE (PS_Day2_ID ASC) VISIBLE,
ADD INDEX fk_ps_day2_mouse_id_idx (MouseID ASC) VISIBLE, 
ADD CONSTRAINT fk_ps_day2_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT un_ps2_mouse_id_time UNIQUE(MouseID, PS_Day2_Time),
ADD CONSTRAINT fk_ps_day2_day1
  FOREIGN KEY (MouseID)
  REFERENCES ps_t01 (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;




-- ts
  
ALTER TABLE ts_sum_t01 
CHANGE COLUMN TS_SUM_ID TS_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN TS_TrialNumber TS_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN TS_AgeInDays TS_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN TS_ExperimentTime TS_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN TS_Notes TS_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD PRIMARY KEY (TS_SUM_ID),
ADD UNIQUE INDEX TS_SUM_ID_UNIQUE (TS_SUM_ID ASC) VISIBLE,
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_ts_sum_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  

ALTER TABLE ts_t01 
CHANGE COLUMN TS_ID TS_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN TS_TrialNumber TS_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN TS_Time TS_Time TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN TS_Immobility TS_Immobility DECIMAL(4,1) NULL DEFAULT NULL ,
CHANGE COLUMN TS_Distance TS_Distance DECIMAL(7,1) NULL DEFAULT NULL ,

ADD PRIMARY KEY (TS_ID),
ADD UNIQUE INDEX TS_ID_UNIQUE (TS_ID ASC) VISIBLE,
ADD INDEX fk_ts_mouse_id_idx (MouseID ASC) VISIBLE, 
ADD CONSTRAINT fk_ts_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT un_ts_mouse_id_time UNIQUE(MouseID, TS_Time);






-- hc
  
  
ALTER TABLE hc_sum_t01 
CHANGE COLUMN HC_SUM_ID HC_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN HC_TrialID HC_TrialID VARCHAR(45) NOT NULL ,
CHANGE COLUMN HC_Notes HC_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD PRIMARY KEY (HC_SUM_ID),
ADD UNIQUE INDEX HC_SUM_ID_UNIQUE (HC_SUM_ID ASC) VISIBLE,
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_hc_sum_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD INDEX HC_TrialID (HC_TrialID ASC) VISIBLE;



ALTER TABLE hc_t01 
CHANGE COLUMN HC_ID HC_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN HC_TrialID HC_TrialID VARCHAR(45) NOT NULL ,
CHANGE COLUMN HC_HourRecorded HC_HourRecorded TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN HC_NumberOfRecords HC_NumberOfRecords SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN HC_TotalLatency HC_TotalLatency MEDIUMINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN HC_Time HC_Time SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN HC_AverageDistribution HC_AverageDistribution DECIMAL(4,3) NULL DEFAULT NULL ,
CHANGE COLUMN HC_TotalArea HC_TotalArea MEDIUMINT UNSIGNED NULL DEFAULT NULL ,

ADD PRIMARY KEY (HC_ID),
ADD UNIQUE INDEX HC_ID_UNIQUE (HC_ID ASC) VISIBLE, 
ADD CONSTRAINT fk_hc_trial_id
  FOREIGN KEY (HC_TrialID)
  REFERENCES hc_sum_t01 (HC_TrialID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT un_hc_trial_id_time UNIQUE(HC_TrialID, HC_Time);



-- si

ALTER TABLE si_sum_t01 
CHANGE COLUMN SI_SUM_ID SI_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN SI_TrialNumber SI_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN SI_TrialID SI_TrialID VARCHAR(45) NOT NULL ,
CHANGE COLUMN SI_AgeInDays SI_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN SI_OrderInCage SI_OrderInCage TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN SI_TotalDistance SI_TotalDistance DECIMAL(7,1) NULL DEFAULT NULL ,

ADD PRIMARY KEY (SI_SUM_ID),
ADD UNIQUE INDEX SI_SUM_ID_UNIQUE (SI_SUM_ID ASC) VISIBLE,
ADD UNIQUE INDEX MouseID_UNIQUE (MouseID ASC) VISIBLE,
ADD INDEX SI_TrialID_INDEX (SI_TrialID ASC) VISIBLE,
ADD CONSTRAINT fk_si_sum_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


ALTER TABLE si_t01 
CHANGE COLUMN SI_ID SI_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN SI_TrialNumber SI_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN SI_TrialID SI_TrialID VARCHAR(45) NOT NULL ,
CHANGE COLUMN SI_ExperimentTime SI_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN SI_NumTotalContacts SI_NumTotalContacts SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN SI_Notes SI_Notes VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN SI_AverageTotalDistance SI_AverageTotalDistance DECIMAL(7,1) NULL DEFAULT NULL ,
CHANGE COLUMN SI_TotalDurActiveContact_sec SI_TotalDurActiveContact_sec DECIMAL(7,1) NULL DEFAULT NULL ,
CHANGE COLUMN SI_TotalDurContact_sec SI_TotalDurContact_sec DECIMAL(7,1) NULL DEFAULT NULL ,

ADD PRIMARY KEY (SI_ID),
ADD UNIQUE INDEX SI_ID_UNIQUE (SI_ID ASC) VISIBLE,
ADD UNIQUE INDEX SI_TrialID_UNIQUE (SI_TrialID ASC) VISIBLE, 
ADD CONSTRAINT fk_si_trial_id
  FOREIGN KEY (SI_TrialID)
  REFERENCES si_sum_t01 (SI_TrialID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;



-- tm

ALTER TABLE tm_t01 
CHANGE COLUMN TM_ID TM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN TM_ExperimentTime TM_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN TM_AgeInDays TM_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN TM_NumberOfFreeChoices TM_NumberOfFreeChoices TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN TM_Error TM_Error TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN TM_NumberOfCorrectResponses TM_NumberOfCorrectResponses TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN TM_Time TM_Time TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN TM_Notes TM_Notes VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN TM_TotalDistance TM_TotalDistance DECIMAL(7,1) NULL DEFAULT NULL ,
CHANGE COLUMN TM_Latency TM_Latency SMALLINT UNSIGNED NULL DEFAULT NULL ,

ADD PRIMARY KEY (TM_ID),
ADD UNIQUE INDEX TM_ID_UNIQUE (TM_ID ASC) VISIBLE,
ADD INDEX fk_tm_mouse_id_idx (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_tm_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT un_tm_mouse_id_time UNIQUE(MouseID, TM_Time);


-- bm

ALTER TABLE bm_t01 
CHANGE COLUMN BM_ID BM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN BM_ExperimentTime BM_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN BM_AgeInDays BM_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_TrialNumber BM_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN BM_SubTrialNumber BM_SubTrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN BM_ErrorsTo1st BM_ErrorsTo1st TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_LatencyTo1st BM_LatencyTo1st SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_LatencyToEnter BM_LatencyToEnter SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_MovingTime BM_MovingTime SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_MultipleParticles BM_MultipleParticles SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_NoParticles BM_NoParticles SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_OmissionErrors BM_OmissionErrors SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_TimeAroundTarget BM_TimeAroundTarget SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_TotalErrors BM_TotalErrors SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_Time BM_Time TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_DistanceTo1st BM_DistanceTo1st DECIMAL(9,2) NULL DEFAULT NULL ,
CHANGE COLUMN BM_TotalDistance BM_TotalDistance DECIMAL(9,2) NULL DEFAULT NULL ,
CHANGE COLUMN BM_TotalSpeed BM_TotalSpeed DECIMAL(9,2) NULL DEFAULT NULL ,
CHANGE COLUMN BM_Notes BM_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD PRIMARY KEY (BM_ID),
ADD UNIQUE INDEX BM_ID_UNIQUE (BM_ID ASC) VISIBLE,
ADD INDEX fk_bm_mouse_id_idx (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_bm_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD UNIQUE INDEX un_bm_mouse_id_sub (MouseID ASC, BM_SubTrialNumber ASC) VISIBLE;



  -- bm probe
  
ALTER TABLE bm_probe_sum_t01 
CHANGE COLUMN BM_probe_SUM_ID BM_probe_SUM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN BM_probe_SUM_ExperimentTime BM_probe_SUM_ExperimentTime TIME NULL DEFAULT NULL ,
CHANGE COLUMN BM_probe_SUM_AgeInDays BM_probe_SUM_AgeInDays SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_probe_SUM_TrialNumber BM_probe_SUM_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN BM_probe_SUM_SubTrialNumber BM_probe_SUM_SubTrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN BM_probe_SUM_Target BM_probe_SUM_Target TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_probe_SUM_Notes BM_probe_SUM_Notes VARCHAR(400) NULL DEFAULT NULL ,

ADD PRIMARY KEY (BM_probe_SUM_ID),
ADD UNIQUE INDEX BM_probe_SUM_ID_UNIQUE (BM_probe_SUM_ID ASC) VISIBLE,
ADD INDEX fk_bm_probe_mouse_id_idx (MouseID ASC) VISIBLE,
ADD CONSTRAINT fk_bm_probe_sum_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD UNIQUE INDEX un_bm_probe_sum_mouse_id_sub (MouseID ASC, BM_probe_SUM_SubTrialNumber ASC) VISIBLE;

  
ALTER TABLE bm_probe_t01 
CHANGE COLUMN BM_probe_ID BM_probe_ID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN MouseID MouseID VARCHAR(45) NOT NULL ,
CHANGE COLUMN BM_probe_TrialNumber BM_probe_TrialNumber VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN BM_probe_N BM_probe_N TINYINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_probe_Time BM_probe_Time SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_probe_Around_hole_Time BM_probe_Around_hole_Time SMALLINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN BM_probe_Notes BM_probe_Notes VARCHAR(400) NULL DEFAULT NULL ,
CHANGE COLUMN BM_probe_SubTrialNumber BM_probe_SubTrialNumber VARCHAR(15) NOT NULL ,
CHANGE COLUMN BM_probe_Angle BM_probe_Angle SMALLINT NOT NULL ,

ADD PRIMARY KEY (BM_probe_ID),
ADD UNIQUE INDEX BM_probe_ID_UNIQUE (BM_probe_ID ASC) VISIBLE,
ADD INDEX fk_bm_probe_mouse_id_idx (MouseID ASC) VISIBLE, 
ADD CONSTRAINT fk_bm_probe_mouse_id
  FOREIGN KEY (MouseID)
  REFERENCES mouse_info (MouseID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD UNIQUE INDEX un_bm_probe_mouse_id_sub_angle (MouseID ASC, BM_probe_SubTrialNumber ASC, BM_probe_Angle ASC) VISIBLE;




